"""Complete SQLAlchemy model registry used by runtime and Alembic."""

from app.models.access import Session, StaffInvite, StaffMember, StaffPermission, User
from app.models.audit import AuditEvent
from app.models.cards import UserCard
from app.models.content import (
    AppSetting,
    Location,
    MenuCategory,
    MenuItem,
    MenuItemModifierGroup,
    ModifierGroup,
    ModifierOption,
    Promotion,
    PromotionMenuCategory,
    PromotionMenuItem,
    Venue,
)
from app.models.customers import CustomerIdentity, CustomerMerge
from app.models.delivery import Broadcast, BroadcastDelivery, NotificationOutbox
from app.models.engagement import (
    BulkBonusBatch,
    BulkBonusItem,
    CustomerPass,
    PassPurchase,
    PassTemplate,
    PassTemplateCategory,
    PassTemplateItem,
    PassTemplateVenue,
    PassUsage,
    PublicReview,
)
from app.models.loyalty import (
    LoyaltyOperation,
    LoyaltySettings,
    PointTransaction,
    Reward,
    RewardTemplate,
    StampTransaction,
    UserLoyaltyState,
    Visit,
)
from app.models.loyalty_v2 import (
    AccountMergeLotRoute,
    BirthdayPromotionVenue,
    LoyaltyWallet,
    PointAllocation,
    PointLot,
    PointLotRoute,
    WalletModeSwitch,
    WalletTransfer,
)
from app.models.media import MediaFile
from app.models.orders import (
    CustomerOrder,
    DeliverySettings,
    DeliveryZone,
    OrderAppliedPromotion,
    OrderEvent,
    OrderLine,
    OrderLineModifier,
    OrderPointRedemption,
    OrderSuborder,
)
from app.models.receipts import Receipt, ReceiptRevision, ReceiptRiskFlag, ReceiptRiskSettings
from app.models.staff import FeedbackItem, StaffTipProfile

__all__ = [
    "AccountMergeLotRoute",
    "AppSetting",
    "AuditEvent",
    "BirthdayPromotionVenue",
    "Broadcast",
    "BroadcastDelivery",
    "BulkBonusBatch",
    "BulkBonusItem",
    "CustomerIdentity",
    "CustomerMerge",
    "CustomerOrder",
    "CustomerPass",
    "DeliverySettings",
    "DeliveryZone",
    "FeedbackItem",
    "Location",
    "LoyaltyOperation",
    "LoyaltySettings",
    "LoyaltyWallet",
    "MediaFile",
    "MenuCategory",
    "MenuItem",
    "MenuItemModifierGroup",
    "ModifierGroup",
    "ModifierOption",
    "NotificationOutbox",
    "OrderAppliedPromotion",
    "OrderEvent",
    "OrderLine",
    "OrderLineModifier",
    "OrderPointRedemption",
    "OrderSuborder",
    "PassPurchase",
    "PassTemplate",
    "PassTemplateCategory",
    "PassTemplateItem",
    "PassTemplateVenue",
    "PassUsage",
    "PointAllocation",
    "PointLot",
    "PointLotRoute",
    "PointTransaction",
    "Promotion",
    "PromotionMenuCategory",
    "PromotionMenuItem",
    "PublicReview",
    "Receipt",
    "ReceiptRevision",
    "ReceiptRiskFlag",
    "ReceiptRiskSettings",
    "Reward",
    "RewardTemplate",
    "Session",
    "StaffInvite",
    "StaffMember",
    "StaffPermission",
    "StaffTipProfile",
    "StampTransaction",
    "User",
    "UserCard",
    "UserLoyaltyState",
    "Venue",
    "Visit",
    "WalletModeSwitch",
    "WalletTransfer",
]
