"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-21 22:43:35.817848
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "business_day_boundary_minutes", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("map_url", sa.String(length=2048), nullable=True),
        sa.Column("opening_hours", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "business_day_boundary_minutes >= 0 AND business_day_boundary_minutes < 1440",
            name=op.f("ck_locations_valid_business_day_boundary"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name=op.f("ck_locations_valid_latitude"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name=op.f("ck_locations_valid_longitude"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("slug", name=op.f("uq_locations_slug")),
    )
    op.create_index(
        "ix_locations_active_sort", "locations", ["is_active", "sort_order"], unique=False
    )
    op.create_index(
        "uq_locations_one_default",
        "locations",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )
    op.create_table(
        "menu_categories",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menu_categories")),
    )
    op.create_index(
        "ix_menu_categories_visible_sort",
        "menu_categories",
        ["is_visible", "sort_order"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("photo_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "blocked",
                "inactive",
                "anonymized",
                name="user_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("internal_note", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
    )
    op.create_index("ix_users_status", "users", ["status"], unique=False)
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_table(
        "media_files",
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("detected_mime", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                "deleted",
                name="media_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_media_files_positive_byte_size")),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_media_files_uploaded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_files_storage_key")),
    )
    op.create_index("ix_media_files_sha256", "media_files", ["sha256"], unique=False)
    op.create_index("ix_media_files_status", "media_files", ["status"], unique=False)
    op.create_table(
        "notification_outbox",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "sent",
                "failed",
                name="outbox_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_notification_outbox_non_negative_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_outbox_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_outbox")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_notification_outbox_idempotency_key")),
    )
    op.create_index(
        "ix_notification_outbox_claim",
        "notification_outbox",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.String(length=256), nullable=True),
        sa.Column("created_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"], unique=False)
    op.create_index(
        "ix_sessions_user_active", "sessions", ["user_id", "expires_at", "revoked_at"], unique=False
    )
    op.create_table(
        "staff_members",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "customer",
                "staff",
                "admin",
                "owner",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="staff",
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("position", sa.String(length=128), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_edit_tip_profile", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role <> 'customer'", name=op.f("ck_staff_members_role_not_customer")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_staff_members_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_members")),
        sa.UniqueConstraint("user_id", name=op.f("uq_staff_members_user_id")),
    )
    op.create_index(
        "ix_staff_members_role_active", "staff_members", ["role", "is_active"], unique=False
    )
    op.create_table(
        "user_loyalty_states",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("points_balance", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("visit_streak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_visit_business_date", sa.Date(), nullable=True),
        sa.Column("visit_cycle_started_on", sa.Date(), nullable=True),
        sa.Column("allowed_misses_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("stamp_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points_balance >= 0", name=op.f("ck_user_loyalty_states_non_negative_points_balance")
        ),
        sa.CheckConstraint(
            "stamp_count >= 0", name=op.f("ck_user_loyalty_states_non_negative_stamp_count")
        ),
        sa.CheckConstraint(
            "visit_streak >= 0", name=op.f("ck_user_loyalty_states_non_negative_visit_streak")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_loyalty_states_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_loyalty_states")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_loyalty_states_user_id")),
    )
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("updated_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_app_settings_updated_by_staff_id_staff_members"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_app_settings_key")),
    )
    op.create_table(
        "audit_events",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_staff_id", sa.Uuid(), nullable=True),
        sa.Column("subject_user_id", sa.Uuid(), nullable=True),
        sa.Column("object_type", sa.String(length=80), nullable=True),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "warning",
                "critical",
                name="audit_severity",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="info",
            nullable=False,
        ),
        sa.Column("is_suspicious", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_audit_events_actor_staff_id_staff_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_subject_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_actor", "audit_events", ["actor_user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_created_type", "audit_events", ["created_at", "event_type"], unique=False
    )
    op.create_index(
        "ix_audit_events_subject", "audit_events", ["subject_user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_suspicious", "audit_events", ["is_suspicious", "created_at"], unique=False
    )
    op.create_table(
        "broadcasts",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("image_media_id", sa.Uuid(), nullable=True),
        sa.Column("button_label", sa.String(length=80), nullable=True),
        sa.Column("button_url", sa.String(length=2048), nullable=True),
        sa.Column("audience_filter", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "confirmed",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="broadcast_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column("confirmed_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("success_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("skipped_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "success_count >= 0 AND failure_count >= 0 AND skipped_count >= 0",
            name=op.f("ck_broadcasts_non_negative_delivery_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_broadcasts_confirmed_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_broadcasts_created_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["image_media_id"],
            ["media_files.id"],
            name=op.f("fk_broadcasts_image_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcasts")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_broadcasts_idempotency_key")),
    )
    op.create_index(
        "ix_broadcasts_status_created", "broadcasts", ["status", "created_at"], unique=False
    )
    op.create_table(
        "feedback_items",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "service",
                "food_and_drinks",
                "application",
                "loyalty",
                "other",
                name="feedback_category",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("may_contact", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "in_progress",
                "resolved",
                "archived",
                name="feedback_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("assigned_to_staff_id", sa.Uuid(), nullable=True),
        sa.Column("internal_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name=op.f("ck_feedback_items_rating_between_1_and_5")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_feedback_items_assigned_to_staff_id_staff_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_feedback_items_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_items")),
    )
    op.create_index(
        "ix_feedback_items_status_created", "feedback_items", ["status", "created_at"], unique=False
    )
    op.create_index("ix_feedback_items_user_id", "feedback_items", ["user_id"], unique=False)
    op.create_table(
        "loyalty_operations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_staff_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column(
            "operation_type",
            sa.Enum(
                "purchase_accrual",
                "points_redemption",
                "welcome_bonus",
                "admin_adjustment",
                "operation_reversal",
                "points_expiration",
                "visit_mark",
                "stamp_added",
                "reward_created",
                "reward_redeemed",
                "reward_cancelled",
                name="loyalty_operation_type",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "committed",
                "rejected",
                "reversed",
                "failed",
                name="operation_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="committed",
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("purchase_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("points_delta", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("balance_before", sa.BigInteger(), nullable=True),
        sa.Column("balance_after", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purchase_amount_minor IS NULL OR purchase_amount_minor > 0",
            name=op.f("ck_loyalty_operations_positive_purchase"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_loyalty_operations_actor_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_loyalty_operations_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_loyalty_operations_approved_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_loyalty_operations_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_loyalty_operations_reversal_of_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_loyalty_operations_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_operations")),
        sa.UniqueConstraint("operation_type", "idempotency_key", name="operation_type_idempotency"),
        sa.UniqueConstraint("reversal_of_id", name=op.f("uq_loyalty_operations_reversal_of_id")),
    )
    op.create_index(
        "ix_loyalty_operations_actor_created",
        "loyalty_operations",
        ["actor_staff_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_loyalty_operations_status_created",
        "loyalty_operations",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_loyalty_operations_user_created",
        "loyalty_operations",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "menu_items",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_media_id", sa.Uuid(), nullable=True),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("old_price_minor", sa.BigInteger(), nullable=True),
        sa.Column("composition", sa.Text(), nullable=True),
        sa.Column("volume", sa.String(length=80), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "old_price_minor IS NULL OR old_price_minor >= 0",
            name=op.f("ck_menu_items_non_negative_old_price"),
        ),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_menu_items_non_negative_price")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["menu_categories.id"],
            name=op.f("fk_menu_items_category_id_menu_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["image_media_id"],
            ["media_files.id"],
            name=op.f("fk_menu_items_image_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menu_items")),
    )
    op.create_index("ix_menu_items_available", "menu_items", ["is_available"], unique=False)
    op.create_index(
        "ix_menu_items_category_visible_sort",
        "menu_items",
        ["category_id", "is_visible", "sort_order"],
        unique=False,
    )
    op.create_table(
        "promotions",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("image_media_id", sa.Uuid(), nullable=True),
        sa.Column("button_label", sa.String(length=80), nullable=True),
        sa.Column("button_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "scheduled",
                "published",
                "archived",
                name="promotion_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_promotions_valid_publication_window"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_promotions_created_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["image_media_id"],
            ["media_files.id"],
            name=op.f("fk_promotions_image_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
    )
    op.create_index(
        "ix_promotions_status_window",
        "promotions",
        ["status", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_table(
        "reward_templates",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_media_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reward_type",
            sa.Enum(
                "free_product",
                "percent_discount",
                "fixed_discount",
                "free_option",
                "text",
                name="reward_type",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_program",
            sa.Enum(
                "points",
                "visits",
                "stamps",
                "manual",
                name="loyalty_program",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("value_int", sa.BigInteger(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("validity_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validity_days IS NULL OR validity_days > 0",
            name=op.f("ck_reward_templates_positive_validity_days"),
        ),
        sa.CheckConstraint(
            "value_int IS NULL OR value_int >= 0",
            name=op.f("ck_reward_templates_non_negative_value"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_reward_templates_created_by_staff_id_staff_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["image_media_id"],
            ["media_files.id"],
            name=op.f("fk_reward_templates_image_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reward_templates")),
    )
    op.create_index(
        "ix_reward_templates_program_active",
        "reward_templates",
        ["source_program", "is_active"],
        unique=False,
    )
    op.create_table(
        "staff_invites",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("target_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "customer",
                "staff",
                "admin",
                "owner",
                name="invite_role",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="staff",
            nullable=False,
        ),
        sa.Column("invited_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role <> 'customer'", name=op.f("ck_staff_invites_role_not_customer")),
        sa.ForeignKeyConstraint(
            ["invited_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_staff_invites_invited_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["used_by_user_id"],
            ["users.id"],
            name=op.f("fk_staff_invites_used_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_invites")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_staff_invites_token_hash")),
    )
    op.create_index("ix_staff_invites_expires_at", "staff_invites", ["expires_at"], unique=False)
    op.create_index(
        "ix_staff_invites_target_telegram_id", "staff_invites", ["target_telegram_id"], unique=False
    )
    op.create_table(
        "staff_permissions",
        sa.Column("staff_member_id", sa.Uuid(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum(
                "card.lookup",
                "points.accrue",
                "points.redeem",
                "visits.mark",
                "stamps.add",
                "rewards.redeem",
                "operations.reverse_own",
                "tip_profile.manage_own",
                "admin.users.read",
                "admin.users.manage",
                "admin.staff.manage",
                "admin.events.read",
                "admin.settings.manage",
                "admin.content.manage",
                "admin.broadcasts.manage",
                "admin.feedback.manage",
                "owner.admins.manage",
                "owner.export_data",
                "owner.critical_settings",
                name="permission_code",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["staff_member_id"],
            ["staff_members.id"],
            name=op.f("fk_staff_permissions_staff_member_id_staff_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_permissions")),
    )
    op.create_index(
        "uq_staff_permissions_staff_permission",
        "staff_permissions",
        ["staff_member_id", "permission"],
        unique=True,
    )
    op.create_table(
        "staff_tip_profiles",
        sa.Column("staff_member_id", sa.Uuid(), nullable=False),
        sa.Column("published_name", sa.String(length=128), nullable=True),
        sa.Column("published_bio", sa.Text(), nullable=True),
        sa.Column("published_tip_url", sa.String(length=2048), nullable=True),
        sa.Column("published_photo_media_id", sa.Uuid(), nullable=True),
        sa.Column("published_tip_qr_media_id", sa.Uuid(), nullable=True),
        sa.Column("pending_name", sa.String(length=128), nullable=True),
        sa.Column("pending_bio", sa.Text(), nullable=True),
        sa.Column("pending_tip_url", sa.String(length=2048), nullable=True),
        sa.Column("pending_photo_media_id", sa.Uuid(), nullable=True),
        sa.Column("pending_tip_qr_media_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_review",
                "approved",
                "hidden",
                name="tip_profile_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("moderation_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pending_photo_media_id"],
            ["media_files.id"],
            name=op.f("fk_staff_tip_profiles_pending_photo_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pending_tip_qr_media_id"],
            ["media_files.id"],
            name=op.f("fk_staff_tip_profiles_pending_tip_qr_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["published_photo_media_id"],
            ["media_files.id"],
            name=op.f("fk_staff_tip_profiles_published_photo_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["published_tip_qr_media_id"],
            ["media_files.id"],
            name=op.f("fk_staff_tip_profiles_published_tip_qr_media_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_staff_tip_profiles_reviewed_by_staff_id_staff_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["staff_member_id"],
            ["staff_members.id"],
            name=op.f("fk_staff_tip_profiles_staff_member_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_tip_profiles")),
        sa.UniqueConstraint("staff_member_id", name=op.f("uq_staff_tip_profiles_staff_member_id")),
    )
    op.create_index(
        "ix_staff_tip_profiles_status_visible",
        "staff_tip_profiles",
        ["status", "is_visible"],
        unique=False,
    )
    op.create_table(
        "user_cards",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("qr_token", sa.String(length=128), nullable=False),
        sa.Column("short_code", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "revoked",
                name="card_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("issued_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_user_cards_issued_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_user_cards_revoked_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_cards_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_cards")),
        sa.UniqueConstraint("qr_token", name=op.f("uq_user_cards_qr_token")),
        sa.UniqueConstraint("short_code", name=op.f("uq_user_cards_short_code")),
    )
    op.create_index("ix_user_cards_status", "user_cards", ["status"], unique=False)
    op.create_index(
        "uq_user_cards_one_active_per_user",
        "user_cards",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "broadcast_deliveries",
        sa.Column("broadcast_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "sent",
                "failed",
                "skipped",
                name="delivery_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_broadcast_deliveries_broadcast_id_broadcasts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_broadcast_deliveries_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_deliveries")),
    )
    op.create_index(
        "ix_broadcast_deliveries_claim",
        "broadcast_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "uq_broadcast_deliveries_broadcast_user",
        "broadcast_deliveries",
        ["broadcast_id", "user_id"],
        unique=True,
    )
    op.create_table(
        "loyalty_settings",
        sa.Column("singleton_key", sa.String(length=32), server_default="default", nullable=False),
        sa.Column("currency_name", sa.String(length=64), nullable=False),
        sa.Column("currency_code", sa.String(length=8), nullable=False),
        sa.Column("points_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("minor_units_per_point", sa.BigInteger(), nullable=False),
        sa.Column(
            "redemption_minor_units_per_point",
            sa.BigInteger(),
            server_default="100",
            nullable=False,
        ),
        sa.Column("minimum_purchase_minor", sa.BigInteger(), nullable=False),
        sa.Column("maximum_purchase_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "rounding_mode",
            sa.Enum(
                "floor",
                "half_up",
                "ceiling",
                name="rounding_mode",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="floor",
            nullable=False,
        ),
        sa.Column("maximum_redemption_percent", sa.SmallInteger(), nullable=False),
        sa.Column("minimum_redemption_points", sa.BigInteger(), nullable=False),
        sa.Column("welcome_bonus_points", sa.BigInteger(), nullable=False),
        sa.Column("points_validity_days", sa.Integer(), nullable=True),
        sa.Column("daily_accrual_limit_points", sa.BigInteger(), nullable=True),
        sa.Column("operation_accrual_limit_points", sa.BigInteger(), nullable=True),
        sa.Column("large_operation_threshold_minor", sa.BigInteger(), nullable=True),
        sa.Column(
            "large_operation_requires_approval",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("visits_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("visit_required_count", sa.Integer(), nullable=False),
        sa.Column(
            "visits_must_be_consecutive", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("visit_daily_limit", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("business_day_boundary_minutes", sa.Integer(), nullable=False),
        sa.Column("visit_allowed_misses", sa.Integer(), nullable=False),
        sa.Column("visit_reset_on_miss", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("visit_reward_template_id", sa.Uuid(), nullable=True),
        sa.Column("visit_reward_validity_days", sa.Integer(), nullable=True),
        sa.Column("visit_restart_cycle", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("stamps_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("stamp_required_count", sa.Integer(), nullable=False),
        sa.Column("stamps_per_purchase", sa.Integer(), nullable=False),
        sa.Column("stamp_operation_limit", sa.Integer(), nullable=False),
        sa.Column("stamp_reward_template_id", sa.Uuid(), nullable=True),
        sa.Column("stamp_reward_validity_days", sa.Integer(), nullable=True),
        sa.Column("reset_stamps_after_reward", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("updated_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "business_day_boundary_minutes >= 0 AND business_day_boundary_minutes < 1440",
            name=op.f("ck_loyalty_settings_valid_business_day_boundary"),
        ),
        sa.CheckConstraint(
            "maximum_purchase_minor > 0", name=op.f("ck_loyalty_settings_positive_maximum_purchase")
        ),
        sa.CheckConstraint(
            "maximum_redemption_percent >= 0 AND maximum_redemption_percent <= 100",
            name=op.f("ck_loyalty_settings_redemption_percent_between_0_and_100"),
        ),
        sa.CheckConstraint(
            "minimum_purchase_minor >= 0",
            name=op.f("ck_loyalty_settings_non_negative_minimum_purchase"),
        ),
        sa.CheckConstraint(
            "minimum_redemption_points >= 0",
            name=op.f("ck_loyalty_settings_non_negative_minimum_redemption"),
        ),
        sa.CheckConstraint(
            "minor_units_per_point > 0",
            name=op.f("ck_loyalty_settings_positive_minor_units_per_point"),
        ),
        sa.CheckConstraint(
            "redemption_minor_units_per_point > 0",
            name=op.f("ck_loyalty_settings_positive_redemption_minor_units_per_point"),
        ),
        sa.CheckConstraint(
            "stamp_operation_limit > 0",
            name=op.f("ck_loyalty_settings_positive_stamp_operation_limit"),
        ),
        sa.CheckConstraint(
            "stamp_required_count > 0",
            name=op.f("ck_loyalty_settings_positive_stamp_required_count"),
        ),
        sa.CheckConstraint(
            "stamps_per_purchase > 0", name=op.f("ck_loyalty_settings_positive_stamps_per_purchase")
        ),
        sa.CheckConstraint(
            "visit_allowed_misses >= 0",
            name=op.f("ck_loyalty_settings_non_negative_visit_allowed_misses"),
        ),
        sa.CheckConstraint(
            "visit_daily_limit > 0", name=op.f("ck_loyalty_settings_positive_visit_daily_limit")
        ),
        sa.CheckConstraint(
            "visit_required_count > 0",
            name=op.f("ck_loyalty_settings_positive_visit_required_count"),
        ),
        sa.CheckConstraint(
            "welcome_bonus_points >= 0", name=op.f("ck_loyalty_settings_non_negative_welcome_bonus")
        ),
        sa.ForeignKeyConstraint(
            ["stamp_reward_template_id"],
            ["reward_templates.id"],
            name=op.f("fk_loyalty_settings_stamp_reward_template_id_reward_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_loyalty_settings_updated_by_staff_id_staff_members"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["visit_reward_template_id"],
            ["reward_templates.id"],
            name=op.f("fk_loyalty_settings_visit_reward_template_id_reward_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loyalty_settings")),
        sa.UniqueConstraint("singleton_key", name=op.f("uq_loyalty_settings_singleton_key")),
    )
    op.create_table(
        "point_transactions",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delta", sa.BigInteger(), nullable=False),
        sa.Column("balance_before", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("purchase_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "balance_before >= 0 AND balance_after >= 0",
            name=op.f("ck_point_transactions_non_negative_balances"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_point_transactions_operation_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_point_transactions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_point_transactions")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_point_transactions_operation_id")),
    )
    op.create_index(
        "ix_point_transactions_user_created",
        "point_transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "rewards",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("source_operation_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "reward_type",
            sa.Enum(
                "free_product",
                "percent_discount",
                "fixed_discount",
                "free_option",
                "text",
                name="issued_reward_type",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("value_int", sa.BigInteger(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "redeemed",
                "expired",
                "cancelled",
                name="reward_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("redemption_operation_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("cancellation_operation_id", sa.Uuid(), nullable=True),
        sa.Column("internal_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > created_at",
            name=op.f("ck_rewards_expiration_after_creation"),
        ),
        sa.ForeignKeyConstraint(
            ["cancellation_operation_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_rewards_cancellation_operation_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_rewards_cancelled_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_rewards_redeemed_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["redemption_operation_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_rewards_redemption_operation_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_operation_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_rewards_source_operation_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["reward_templates.id"],
            name=op.f("fk_rewards_template_id_reward_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_rewards_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rewards")),
        sa.UniqueConstraint(
            "cancellation_operation_id", name=op.f("uq_rewards_cancellation_operation_id")
        ),
        sa.UniqueConstraint(
            "redemption_operation_id", name=op.f("uq_rewards_redemption_operation_id")
        ),
    )
    op.create_index("ix_rewards_status_expires", "rewards", ["status", "expires_at"], unique=False)
    op.create_index(
        "ix_rewards_user_status_expires",
        "rewards",
        ["user_id", "status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "visits",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("staff_member_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("ordinal", sa.Integer(), server_default="1", nullable=False),
        sa.Column("visited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("streak_after", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("ordinal > 0", name=op.f("ck_visits_positive_ordinal")),
        sa.CheckConstraint("streak_after >= 0", name=op.f("ck_visits_non_negative_streak_after")),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_visits_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_visits_operation_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["staff_member_id"],
            ["staff_members.id"],
            name=op.f("fk_visits_staff_member_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_visits_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visits")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_visits_operation_id")),
        sa.UniqueConstraint(
            "user_id", "business_date", "ordinal", name="user_business_date_ordinal"
        ),
    )
    op.create_index("ix_visits_business_date", "visits", ["business_date"], unique=False)
    op.create_table(
        "stamp_transactions",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("stamps_before", sa.Integer(), nullable=False),
        sa.Column("stamps_after", sa.Integer(), nullable=False),
        sa.Column("issued_reward_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("delta <> 0", name=op.f("ck_stamp_transactions_non_zero_delta")),
        sa.CheckConstraint(
            "stamps_before >= 0 AND stamps_after >= 0",
            name=op.f("ck_stamp_transactions_non_negative_stamps"),
        ),
        sa.ForeignKeyConstraint(
            ["issued_reward_id"],
            ["rewards.id"],
            name=op.f("fk_stamp_transactions_issued_reward_id_rewards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_stamp_transactions_operation_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_stamp_transactions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stamp_transactions")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_stamp_transactions_operation_id")),
    )
    op.create_index(
        "ix_stamp_transactions_user_created",
        "stamp_transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stamp_transactions_user_created", table_name="stamp_transactions")
    op.drop_table("stamp_transactions")
    op.drop_index("ix_visits_business_date", table_name="visits")
    op.drop_table("visits")
    op.drop_index("ix_rewards_user_status_expires", table_name="rewards")
    op.drop_index("ix_rewards_status_expires", table_name="rewards")
    op.drop_table("rewards")
    op.drop_index("ix_point_transactions_user_created", table_name="point_transactions")
    op.drop_table("point_transactions")
    op.drop_table("loyalty_settings")
    op.drop_index("uq_broadcast_deliveries_broadcast_user", table_name="broadcast_deliveries")
    op.drop_index("ix_broadcast_deliveries_claim", table_name="broadcast_deliveries")
    op.drop_table("broadcast_deliveries")
    op.drop_index(
        "uq_user_cards_one_active_per_user",
        table_name="user_cards",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_user_cards_status", table_name="user_cards")
    op.drop_table("user_cards")
    op.drop_index("ix_staff_tip_profiles_status_visible", table_name="staff_tip_profiles")
    op.drop_table("staff_tip_profiles")
    op.drop_index("uq_staff_permissions_staff_permission", table_name="staff_permissions")
    op.drop_table("staff_permissions")
    op.drop_index("ix_staff_invites_target_telegram_id", table_name="staff_invites")
    op.drop_index("ix_staff_invites_expires_at", table_name="staff_invites")
    op.drop_table("staff_invites")
    op.drop_index("ix_reward_templates_program_active", table_name="reward_templates")
    op.drop_table("reward_templates")
    op.drop_index("ix_promotions_status_window", table_name="promotions")
    op.drop_table("promotions")
    op.drop_index("ix_menu_items_category_visible_sort", table_name="menu_items")
    op.drop_index("ix_menu_items_available", table_name="menu_items")
    op.drop_table("menu_items")
    op.drop_index("ix_loyalty_operations_user_created", table_name="loyalty_operations")
    op.drop_index("ix_loyalty_operations_status_created", table_name="loyalty_operations")
    op.drop_index("ix_loyalty_operations_actor_created", table_name="loyalty_operations")
    op.drop_table("loyalty_operations")
    op.drop_index("ix_feedback_items_user_id", table_name="feedback_items")
    op.drop_index("ix_feedback_items_status_created", table_name="feedback_items")
    op.drop_table("feedback_items")
    op.drop_index("ix_broadcasts_status_created", table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index("ix_audit_events_suspicious", table_name="audit_events")
    op.drop_index("ix_audit_events_subject", table_name="audit_events")
    op.drop_index("ix_audit_events_created_type", table_name="audit_events")
    op.drop_index("ix_audit_events_actor", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("app_settings")
    op.drop_table("user_loyalty_states")
    op.drop_index("ix_staff_members_role_active", table_name="staff_members")
    op.drop_table("staff_members")
    op.drop_index("ix_sessions_user_active", table_name="sessions")
    op.drop_index("ix_sessions_expires_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_notification_outbox_claim", table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index("ix_media_files_status", table_name="media_files")
    op.drop_index("ix_media_files_sha256", table_name="media_files")
    op.drop_table("media_files")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_index("ix_users_status", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_menu_categories_visible_sort", table_name="menu_categories")
    op.drop_table("menu_categories")
    op.drop_index(
        "uq_locations_one_default",
        table_name="locations",
        postgresql_where=sa.text("is_default = true"),
    )
    op.drop_index("ix_locations_active_sort", table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
