"""add orders pickup and delivery

Revision ID: 0013
Revises: 0012
Create Date: 2026-08-27 02:04:11.922991
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_zones",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("minimum_order_minor", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fee_minor >= 0", name=op.f("ck_delivery_zones_non_negative_fee")),
        sa.CheckConstraint(
            "minimum_order_minor IS NULL OR minimum_order_minor >= 0",
            name=op.f("ck_delivery_zones_non_negative_minimum_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_zones")),
    )
    op.create_index(
        "ix_delivery_zones_active_sort", "delivery_zones", ["is_active", "sort_order"], unique=False
    )
    op.create_table(
        "customer_orders",
        sa.Column("number", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "fulfillment_mode",
            sa.Enum(
                "pickup",
                "delivery",
                name="order_fulfillment_mode",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "confirmed",
                "preparing",
                "ready",
                "waiting_for_courier",
                "courier_assigned",
                "picked_up",
                "in_transit",
                "delivered",
                "cancelled",
                name="order_status",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("status_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("pickup_location_id", sa.Uuid(), nullable=True),
        sa.Column("consolidation_location_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_zone_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_courier_staff_id", sa.Uuid(), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("entrance", sa.String(length=32), nullable=True),
        sa.Column("apartment", sa.String(length=32), nullable=True),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column("customer_comment", sa.Text(), nullable=True),
        sa.Column("desired_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pickup_name_snapshot", sa.String(length=160), nullable=True),
        sa.Column("pickup_address_snapshot", sa.Text(), nullable=True),
        sa.Column("delivery_zone_name_snapshot", sa.String(length=160), nullable=True),
        sa.Column("subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column("promotion_discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("points_discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("delivery_fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "cash",
                "card_on_receipt",
                name="order_payment_method",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "unpaid",
                "paid_externally",
                "cancelled",
                name="order_payment_status",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            server_default="unpaid",
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status_version >= 1", name=op.f("ck_customer_orders_positive_status_version")
        ),
        sa.CheckConstraint(
            "subtotal_minor >= 0 AND promotion_discount_minor >= 0 "
            "AND points_discount_minor >= 0 AND delivery_fee_minor >= 0 "
            "AND total_minor >= 0",
            name=op.f("ck_customer_orders_non_negative_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_courier_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_customer_orders_assigned_courier_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["consolidation_location_id"],
            ["locations.id"],
            name=op.f("fk_customer_orders_consolidation_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_zone_id"],
            ["delivery_zones.id"],
            name=op.f("fk_customer_orders_delivery_zone_id_delivery_zones"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pickup_location_id"],
            ["locations.id"],
            name=op.f("fk_customer_orders_pickup_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_customer_orders_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_orders")),
        sa.UniqueConstraint("number", name=op.f("uq_customer_orders_number")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="user_order_idempotency"),
    )
    op.create_index(
        "ix_customer_orders_courier_status",
        "customer_orders",
        ["assigned_courier_staff_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_customer_orders_status_created",
        "customer_orders",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_customer_orders_user_created",
        "customer_orders",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "delivery_settings",
        sa.Column("singleton_key", sa.String(length=32), server_default="default", nullable=False),
        sa.Column("delivery_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("minimum_order_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("fixed_fee_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("free_delivery_threshold_minor", sa.BigInteger(), nullable=True),
        sa.Column("scheduling_allowed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "earliest_preparation_minutes", sa.Integer(), server_default="30", nullable=False
        ),
        sa.Column("operating_hours", sa.JSON(), nullable=False),
        sa.Column("default_pickup_location_id", sa.Uuid(), nullable=True),
        sa.Column("consolidation_location_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "earliest_preparation_minutes >= 0",
            name=op.f("ck_delivery_settings_non_negative_earliest_preparation"),
        ),
        sa.CheckConstraint(
            "fixed_fee_minor >= 0", name=op.f("ck_delivery_settings_non_negative_fixed_fee")
        ),
        sa.CheckConstraint(
            "free_delivery_threshold_minor IS NULL OR free_delivery_threshold_minor >= 0",
            name=op.f("ck_delivery_settings_non_negative_free_delivery_threshold"),
        ),
        sa.CheckConstraint(
            "minimum_order_minor >= 0", name=op.f("ck_delivery_settings_non_negative_minimum_order")
        ),
        sa.ForeignKeyConstraint(
            ["consolidation_location_id"],
            ["locations.id"],
            name=op.f("fk_delivery_settings_consolidation_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["default_pickup_location_id"],
            ["locations.id"],
            name=op.f("fk_delivery_settings_default_pickup_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_delivery_settings_updated_by_staff_id_staff_members"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_settings")),
        sa.UniqueConstraint("singleton_key", name=op.f("uq_delivery_settings_singleton_key")),
    )
    op.create_table(
        "order_point_redemptions",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("loyalty_operation_id", sa.Uuid(), nullable=False),
        sa.Column("points", sa.BigInteger(), nullable=False),
        sa.Column("discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points > 0 AND discount_minor > 0",
            name=op.f("ck_order_point_redemptions_positive_redemption"),
        ),
        sa.ForeignKeyConstraint(
            ["loyalty_operation_id"],
            ["loyalty_operations.id"],
            name=op.f("fk_order_point_redemptions_loyalty_operation_id_loyalty_operations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["customer_orders.id"],
            name=op.f("fk_order_point_redemptions_order_id_customer_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
            name=op.f("fk_order_point_redemptions_venue_id_venues"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_point_redemptions")),
        sa.UniqueConstraint(
            "loyalty_operation_id", name=op.f("uq_order_point_redemptions_loyalty_operation_id")
        ),
        sa.UniqueConstraint("order_id", "venue_id", name="order_venue_redemption"),
    )
    op.create_table(
        "order_suborders",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "confirmed",
                "preparing",
                "ready",
                "waiting_for_courier",
                "courier_assigned",
                "picked_up",
                "in_transit",
                "delivered",
                "cancelled",
                name="suborder_status",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column("promotion_discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("points_discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subtotal_minor >= 0 AND promotion_discount_minor >= 0 "
            "AND points_discount_minor >= 0 AND total_minor >= 0",
            name=op.f("ck_order_suborders_non_negative_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["customer_orders.id"],
            name=op.f("fk_order_suborders_order_id_customer_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
            name=op.f("fk_order_suborders_venue_id_venues"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_suborders")),
        sa.UniqueConstraint("order_id", "venue_id", name="order_venue_suborder"),
    )
    op.create_index(
        "ix_order_suborders_venue_status",
        "order_suborders",
        ["venue_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "order_applied_promotions",
        sa.Column("suborder_id", sa.Uuid(), nullable=False),
        sa.Column("promotion_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_minor > 0", name=op.f("ck_order_applied_promotions_positive_discount")
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.id"],
            name=op.f("fk_order_applied_promotions_promotion_id_promotions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["suborder_id"],
            ["order_suborders.id"],
            name=op.f("fk_order_applied_promotions_suborder_id_order_suborders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_applied_promotions")),
        sa.UniqueConstraint("suborder_id", "promotion_id", name="suborder_promotion"),
    )
    op.create_table(
        "order_events",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("suborder_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_staff_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=24), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "new",
                "confirmed",
                "preparing",
                "ready",
                "waiting_for_courier",
                "courier_assigned",
                "picked_up",
                "in_transit",
                "delivered",
                "cancelled",
                name="order_event_from_status",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "new",
                "confirmed",
                "preparing",
                "ready",
                "waiting_for_courier",
                "courier_assigned",
                "picked_up",
                "in_transit",
                "delivered",
                "cancelled",
                name="order_event_to_status",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_order_events_actor_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_order_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["customer_orders.id"],
            name=op.f("fk_order_events_order_id_customer_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["suborder_id"],
            ["order_suborders.id"],
            name=op.f("fk_order_events_suborder_id_order_suborders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index(
        "ix_order_events_order_created",
        "order_events",
        ["order_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "order_lines",
        sa.Column("suborder_id", sa.Uuid(), nullable=False),
        sa.Column("menu_item_id", sa.Uuid(), nullable=True),
        sa.Column("client_line_id", sa.Uuid(), nullable=False),
        sa.Column("item_name", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_base_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("unit_modifiers_price_minor", sa.BigInteger(), nullable=False),
        sa.Column("subtotal_minor", sa.BigInteger(), nullable=False),
        sa.Column("promotion_discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("points_discount_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_lines_positive_quantity")),
        sa.CheckConstraint(
            "unit_base_price_minor >= 0 AND unit_modifiers_price_minor >= 0 "
            "AND subtotal_minor >= 0 AND promotion_discount_minor >= 0 "
            "AND points_discount_minor >= 0 AND total_minor >= 0",
            name=op.f("ck_order_lines_non_negative_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
            name=op.f("fk_order_lines_menu_item_id_menu_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["suborder_id"],
            ["order_suborders.id"],
            name=op.f("fk_order_lines_suborder_id_order_suborders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
    )
    op.create_index(
        "ix_order_lines_suborder_sort", "order_lines", ["suborder_id", "sort_order"], unique=False
    )
    op.create_table(
        "order_line_modifiers",
        sa.Column("order_line_id", sa.Uuid(), nullable=False),
        sa.Column("modifier_option_id", sa.Uuid(), nullable=True),
        sa.Column("group_name", sa.String(length=160), nullable=False),
        sa.Column("option_name", sa.String(length=160), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_delta_minor", sa.BigInteger(), nullable=False),
        sa.Column("total_price_delta_minor", sa.BigInteger(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_line_modifiers_positive_quantity")),
        sa.CheckConstraint(
            "unit_price_delta_minor >= 0 AND total_price_delta_minor >= 0",
            name=op.f("ck_order_line_modifiers_non_negative_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["modifier_option_id"],
            ["modifier_options.id"],
            name=op.f("fk_order_line_modifiers_modifier_option_id_modifier_options"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_order_line_modifiers_order_line_id_order_lines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_line_modifiers")),
    )
    op.create_index(
        "ix_order_line_modifiers_line_sort",
        "order_line_modifiers",
        ["order_line_id", "sort_order"],
        unique=False,
    )
    op.add_column(
        "locations",
        sa.Column("pickup_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "locations",
        sa.Column("consolidation_enabled", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("locations", sa.Column("pickup_comment", sa.Text(), nullable=True))
    op.add_column(
        "locations",
        sa.Column("preparation_minutes", sa.Integer(), server_default="20", nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_locations_non_negative_preparation_minutes"),
        "locations",
        "preparation_minutes >= 0",
    )

    # Permission codes are constrained strings, so extending the Python enum
    # requires replacing the existing PostgreSQL CHECK in the same migration.
    op.drop_constraint(
        op.f("ck_staff_permissions_permission_code"),
        "staff_permissions",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_staff_permissions_permission_code"),
        "staff_permissions",
        "permission IN ('card.lookup', 'customers.create', 'points.accrue', "
        "'points.redeem', 'visits.mark', 'stamps.add', 'rewards.redeem', "
        "'operations.reverse_own', 'tip_profile.manage_own', 'orders.read', "
        "'orders.manage', 'admin.users.read', 'admin.users.manage', "
        "'admin.staff.manage', 'admin.events.read', 'admin.settings.manage', "
        "'admin.content.manage', 'admin.broadcasts.manage', "
        "'admin.feedback.manage', 'admin.delivery.manage', "
        "'owner.admins.manage', 'owner.export_data', 'owner.critical_settings')",
    )

    # Every installation receives one conservative delivery policy. Seed/admin
    # configuration may enable delivery later without relying on application startup.
    op.execute(
        sa.text(
            """
            INSERT INTO delivery_settings (
                id, singleton_key, delivery_enabled, minimum_order_minor,
                fixed_fee_minor, scheduling_allowed,
                earliest_preparation_minutes, operating_hours,
                default_pickup_location_id
            )
            VALUES (
                CAST('00000000-0000-0000-0000-000000000013' AS uuid),
                'default', false, 0, 0, false, 30, CAST('{}' AS json),
                (
                    SELECT id FROM locations
                    WHERE is_active = true AND is_default = true
                    ORDER BY id LIMIT 1
                )
            )
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Order snapshots and event history are operational records. Production
    # rollback uses a verified backup rather than deleting them in-place.
    raise RuntimeError("0013 downgrade is intentionally unsupported")
