"""add manual receipts and risk flags

Revision ID: 0015
Revises: 0014
Create Date: 2026-08-27 10:54:33.076004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipt_risk_settings",
        sa.Column("singleton_key", sa.String(length=32), nullable=False),
        sa.Column("photo_required", sa.Boolean(), nullable=False),
        sa.Column("high_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("staff_hour_limit", sa.Integer(), nullable=False),
        sa.Column("same_amount_day_limit", sa.Integer(), nullable=False),
        sa.Column("customer_day_limit", sa.Integer(), nullable=False),
        sa.Column("staff_cancel_day_limit", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "singleton_key = 'default'", name=op.f("ck_receipt_risk_settings_singleton_key")
        ),
        sa.CheckConstraint(
            "high_amount_minor > 0 AND staff_hour_limit > 0 AND "
            "same_amount_day_limit > 0 AND customer_day_limit > 0 AND "
            "staff_cancel_day_limit > 0",
            name=op.f("ck_receipt_risk_settings_positive_thresholds"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_risk_settings")),
        sa.UniqueConstraint("singleton_key", name=op.f("uq_receipt_risk_settings_singleton_key")),
    )
    op.create_table(
        "receipts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("image_media_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "rkeeper",
                "other_pos",
                name="receipt_source",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("receipt_number", sa.String(length=160), nullable=True),
        sa.Column("fiscal_data", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "cancelled",
                name="receipt_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'cancelled' AND cancelled_at IS NOT NULL) OR "
            "(status = 'active' AND cancelled_at IS NULL)",
            name=op.f("ck_receipts_valid_cancel_state"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_receipts_positive_amount")),
        sa.CheckConstraint("current_revision >= 1", name=op.f("ck_receipts_positive_revision")),
        sa.ForeignKeyConstraint(
            ["cancelled_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_receipts_cancelled_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_receipts_created_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["image_media_id"],
            ["media_files.id"],
            name=op.f("fk_receipts_image_media_id_media_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_receipts_user_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
            name=op.f("fk_receipts_venue_id_venues"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint("created_by_staff_id", "idempotency_key", name="staff_idempotency"),
        sa.UniqueConstraint("source", "external_id", name="source_external_id"),
    )
    op.create_index(
        "ix_receipts_customer_created", "receipts", ["user_id", "created_at"], unique=False
    )
    op.create_index("ix_receipts_number", "receipts", ["receipt_number"], unique=False)
    op.create_index(
        "ix_receipts_staff_created", "receipts", ["created_by_staff_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_receipts_venue_created", "receipts", ["venue_id", "created_at"], unique=False
    )
    op.create_table(
        "receipt_revisions",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("edited_by_staff_id", sa.Uuid(), nullable=False),
        sa.Column("image_media_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_number", sa.String(length=160), nullable=True),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("fiscal_data", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("change_summary", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_receipt_revisions_positive_revision")),
        sa.ForeignKeyConstraint(
            ["edited_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_receipt_revisions_edited_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["image_media_id"],
            ["media_files.id"],
            name=op.f("fk_receipt_revisions_image_media_id_media_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_revisions_receipt_id_receipts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_revisions")),
        sa.UniqueConstraint("receipt_id", "revision", name="receipt_revision"),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_receipt_revisions_idempotency_key")),
    )
    op.create_index(
        "ix_receipt_revisions_receipt_created",
        "receipt_revisions",
        ["receipt_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "receipt_risk_flags",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_staff_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_risk_flags_receipt_id_receipts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_staff_id"],
            ["staff_members.id"],
            name=op.f("fk_receipt_risk_flags_resolved_by_staff_id_staff_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_risk_flags")),
        sa.UniqueConstraint("receipt_id", "code", name="receipt_code"),
    )
    op.create_index(
        "ix_receipt_risk_flags_open_created",
        "receipt_risk_flags",
        ["resolved_at", "created_at"],
        unique=False,
    )
    # Receipt thresholds are installation data and remain editable in PostgreSQL.
    op.execute(
        sa.text(
            "INSERT INTO receipt_risk_settings "
            "(id, singleton_key, photo_required, high_amount_minor, staff_hour_limit, "
            "same_amount_day_limit, customer_day_limit, staff_cancel_day_limit) VALUES "
            "(CAST('00000000-0000-0000-0000-000000000015' AS uuid), "
            "'default', true, 5000000, 10, 5, 5, 3)"
        )
    )
    op.drop_constraint(
        op.f("ck_staff_permissions_permission_code"), "staff_permissions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_staff_permissions_permission_code"),
        "staff_permissions",
        "permission IN ('card.lookup', 'customers.create', 'points.accrue', "
        "'points.redeem', 'visits.mark', 'stamps.add', 'rewards.redeem', "
        "'operations.reverse_own', 'tip_profile.manage_own', 'orders.read', "
        "'orders.manage', 'courier.orders.read', 'courier.orders.claim', "
        "'courier.orders.update', 'receipts.read', 'receipts.manage', "
        "'admin.users.read', 'admin.users.manage', 'admin.staff.manage', "
        "'admin.events.read', 'admin.settings.manage', 'admin.content.manage', "
        "'admin.broadcasts.manage', 'admin.feedback.manage', "
        "'admin.delivery.manage', 'owner.admins.manage', 'owner.export_data', "
        "'owner.critical_settings')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Receipt/audit history is intentionally never destroyed by an automated rollback.
    raise RuntimeError("0015 downgrade is intentionally unsupported")
